<?php

namespace ContainerSAZdHlq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NY60nlkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NY60nlk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NY60nlk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'snappy' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'snappy' => '?',
        ]);
    }
}
