<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.d94b3b43.js',
                '/build/0.a658fadb.js',
                '/build/app.9fbe2772.js',
            ],
            'css' => [
                '/build/app.0b21aa43.css',
            ],
        ],
    ],
],

]];
